# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b9d4f1737018f6621fef38069f557948b615dc7dccd8e9366b667fb838cbdcacdee76f2c306005933b3b6306edecc28c01d2c3cf25355fe085e665f1b8b2251

test:
  secret_key_base: 15d72be6ec15f9b88cafa7c1236426c0d63585ae6270fd554f2eb64c4a61c9121d8cd482842188427a4fefa65bea608fcaca6cf29ce2951a4910e79f24cffb66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
